import * as fs from "node:fs";
import * as path from "node:path";
import { discoverEntitySources } from "./source-parser";
import {
  GenerateNPAClientOptions,
  GenerateNPARepositoriesOptions,
  GeneratedFile,
  ParsedEntitySource,
} from "./types";

const FIND_ACTIONS = [
  { prefix: "findBy", result: "Promise<$entity[]>" },
  { prefix: "findOneBy", result: "Promise<$entity | null>" },
  { prefix: "existsBy", result: "Promise<boolean>" },
  { prefix: "countBy", result: "Promise<number>" },
  { prefix: "deleteBy", result: "Promise<number>" },
];

const CORE_LIBRARY_IMPORT = "@honeybeaers/npa";
const POSTGRESQL_LIBRARY_IMPORT = "@honeybeaers/npa-pg";
const MYSQL_LIBRARY_IMPORT = "@honeybeaers/npa-mysql";

export function generateNPAClient(
  options: GenerateNPAClientOptions,
): GeneratedFile {
  const outPath = path.resolve(options.cwd, options.out);
  const entities = discoverEntitySources(options.cwd, options.entities);

  if (entities.length === 0) {
    throw new Error(
      `No @Entity classes found for pattern(s): ${options.entities.join(", ")}`,
    );
  }

  const content = renderClient(entities, outPath, options);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, content, "utf8");

  return { path: outPath, content };
}

export function generateNPARepositories(
  options: GenerateNPARepositoriesOptions,
): GeneratedFile {
  const outPath = path.resolve(options.cwd, options.out);
  const entities = discoverEntitySources(options.cwd, options.entities);

  if (entities.length === 0) {
    throw new Error(
      `No @Entity classes found for pattern(s): ${options.entities.join(", ")}`,
    );
  }

  const content = renderRepositoriesFile(entities, outPath, options);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, content, "utf8");

  return { path: outPath, content };
}

function renderClient(
  entities: ParsedEntitySource[],
  outPath: string,
  options: GenerateNPAClientOptions,
): string {
  const imports = renderEntityImports(entities, outPath);
  const repositories = entities.map(renderRepository).join("\n\n");
  const client = renderClientInterface(entities, options);
  const factory = renderFactory(entities, options);

  return [
    "/* eslint-disable */",
    "// This file was generated by npa generate. Do not edit by hand.",
    renderLibraryImport(options),
    imports,
    "",
    repositories,
    "",
    client,
    "",
    factory,
    "",
  ].join("\n");
}

function renderRepositoriesFile(
  entities: ParsedEntitySource[],
  outPath: string,
  options: GenerateNPARepositoriesOptions,
): string {
  const imports = renderEntityImports(entities, outPath);
  const repositories = entities.map(renderRepositoryClass).join("\n\n");
  const registry = renderRepositoryRegistry(entities);

  return [
    "/* eslint-disable */",
    "// This file was generated by npa generate repositories. Do not edit by hand.",
    renderRepositoryLibraryImport(options),
    imports,
    "",
    repositories,
    "",
    registry,
    "",
  ].join("\n");
}

function renderEntityImports(
  entities: ParsedEntitySource[],
  outPath: string,
): string {
  return entities
    .map((entity) => {
      const importPath = toImportPath(entity.filePath, outPath);
      return `import { ${entity.className} } from "${importPath}";`;
    })
    .join("\n");
}

function renderRepository(entity: ParsedEntitySource): string {
  const idType = getIdType(entity);
  const methods = entity.columns.flatMap((column) =>
    renderColumnMethods(
      entity.className,
      column.propertyName,
      column.type,
      column.primary,
    ),
  );

  return [
    `export interface ${entity.className}Repository extends NPARepository<${entity.className}, ${idType}> {`,
    ...methods.map((method) => `  ${method}`),
    "}",
  ].join("\n");
}

function renderRepositoryClass(entity: ParsedEntitySource): string {
  const idType = getIdType(entity);
  const methods = entity.columns.flatMap((column) =>
    renderColumnMethods(
      entity.className,
      column.propertyName,
      column.type,
      column.primary,
    ),
  );

  return [
    `@Repository(${entity.className})`,
    `export abstract class ${entity.className}Repository extends NPARepository<${entity.className}, ${idType}> {`,
    ...methods.map((method) => `  abstract ${method}`),
    "}",
  ].join("\n");
}

function renderColumnMethods(
  entityName: string,
  propertyName: string,
  propertyType: string,
  primary: boolean,
): string[] {
  const suffix = toPascalCase(propertyName);
  const valueType = `NonNullable<${entityName}["${propertyName}"]>`;
  const methods: string[] = [];

  methods.push(
    ...renderActionMethods(entityName, suffix, `value: ${valueType}`).filter(
      (method) => !primary || !method.startsWith(`findBy${suffix}(`),
    ),
  );
  methods.push(...renderActionMethods(entityName, `${suffix}In`, `values: ${valueType}[]`));
  methods.push(...renderActionMethods(entityName, `${suffix}NotIn`, `values: ${valueType}[]`));
  methods.push(...renderActionMethods(entityName, `${suffix}IsNull`, ""));
  methods.push(...renderActionMethods(entityName, `${suffix}IsNotNull`, ""));

  if (isStringType(propertyType)) {
    methods.push(...renderActionMethods(entityName, `${suffix}Containing`, `value: ${valueType}`));
    methods.push(...renderActionMethods(entityName, `${suffix}StartingWith`, `value: ${valueType}`));
    methods.push(...renderActionMethods(entityName, `${suffix}EndingWith`, `value: ${valueType}`));
    methods.push(...renderActionMethods(entityName, `${suffix}Like`, `value: ${valueType}`));
  }

  if (isComparableType(propertyType)) {
    methods.push(...renderActionMethods(entityName, `${suffix}LessThan`, `value: ${valueType}`));
    methods.push(...renderActionMethods(entityName, `${suffix}LessThanEqual`, `value: ${valueType}`));
    methods.push(...renderActionMethods(entityName, `${suffix}GreaterThan`, `value: ${valueType}`));
    methods.push(...renderActionMethods(entityName, `${suffix}GreaterThanEqual`, `value: ${valueType}`));
    methods.push(...renderActionMethods(entityName, `${suffix}Between`, `min: ${valueType}, max: ${valueType}`));
  }

  if (isBooleanType(propertyType)) {
    methods.push(...renderActionMethods(entityName, `${suffix}True`, ""));
    methods.push(...renderActionMethods(entityName, `${suffix}False`, ""));
  }

  return methods;
}

function renderActionMethods(
  entityName: string,
  methodSuffix: string,
  params: string,
): string[] {
  return FIND_ACTIONS.map(
    (action) =>
      `${action.prefix}${methodSuffix}(${params}): ${action.result.replace(
        "$entity",
        entityName,
      )};`,
  );
}

function renderLibraryImport(options: GenerateNPAClientOptions): string {
  const adapterImport =
    options.adapter === "mysql"
      ? "MysqlQueryable, createMysqlDerivedQueryRepository"
      : "PostgresqlQueryable, createPostgresqlDerivedQueryRepository";
  const coreLibraryImport = getCoreLibraryImport(options);
  const adapterLibraryImport = getAdapterLibraryImport(options);

  if (coreLibraryImport === adapterLibraryImport) {
    return `import { NPARepository, ${adapterImport} } from "${coreLibraryImport}";`;
  }

  return [
    `import { NPARepository } from "${coreLibraryImport}";`,
    `import { ${adapterImport} } from "${adapterLibraryImport}";`,
  ].join("\n");
}

function renderRepositoryLibraryImport(
  options: GenerateNPARepositoriesOptions,
): string {
  return `import { NPARepository, Repository } from "${getCoreLibraryImport(options)}";`;
}

function renderRepositoryRegistry(entities: ParsedEntitySource[]): string {
  return [
    "export const npaRepositories = [",
    ...entities.map((entity) => `  ${entity.className}Repository,`),
    "] as const;",
  ].join("\n");
}

function renderClientInterface(
  entities: ParsedEntitySource[],
  options: GenerateNPAClientOptions,
): string {
  const queryableType =
    options.adapter === "mysql" ? "MysqlQueryable" : "PostgresqlQueryable";

  return [
    "export interface NPAClient {",
    ...entities.map(
      (entity) =>
        `  ${toCamelCase(entity.className)}: ${entity.className}Repository;`,
    ),
    "}",
    "",
    "export interface CreateNPAClientOptions {",
    `  ${options.adapter}: {`,
    `    queryable: ${queryableType};`,
    "  };",
    "}",
  ].join("\n");
}

function renderFactory(
  entities: ParsedEntitySource[],
  options: GenerateNPAClientOptions,
): string {
  return [
    "export function createNPAClient(options: CreateNPAClientOptions): NPAClient {",
    "  return {",
    ...entities.map((entity) => {
      const propertyName = toCamelCase(entity.className);
      const idType = getIdType(entity);
      const factory =
        options.adapter === "mysql"
          ? "createMysqlDerivedQueryRepository"
          : "createPostgresqlDerivedQueryRepository";
      return `    ${propertyName}: ${factory}<${entity.className}Repository, ${entity.className}, ${idType}>({} as ${entity.className}Repository, { entity: ${entity.className}, queryable: options.${options.adapter}.queryable }),`;
    }),
    "  };",
    "}",
  ].join("\n");
}

function getIdType(entity: ParsedEntitySource): string {
  return entity.columns.find((column) => column.primary)?.type ?? "unknown";
}

function toImportPath(filePath: string, outPath: string): string {
  const relative = path.relative(path.dirname(outPath), filePath).replace(/\\/g, "/");
  const withoutExtension = relative.replace(/\.[cm]?tsx?$/, "");

  return withoutExtension.startsWith(".")
    ? withoutExtension
    : `./${withoutExtension}`;
}

function toPascalCase(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function toCamelCase(value: string): string {
  return value.charAt(0).toLowerCase() + value.slice(1);
}

function isStringType(value: string): boolean {
  return normalizeType(value) === "string";
}

function isBooleanType(value: string): boolean {
  return normalizeType(value) === "boolean";
}

function isComparableType(value: string): boolean {
  return ["number", "bigint", "Date", "string"].includes(normalizeType(value));
}

function normalizeType(value: string): string {
  return value.replace(/\s*\|\s*undefined/g, "").replace(/\s*\|\s*null/g, "").trim();
}

function getCoreLibraryImport(
  options: GenerateNPAClientOptions | GenerateNPARepositoriesOptions,
): string {
  return options.coreLibraryImport ?? options.libraryImport ?? CORE_LIBRARY_IMPORT;
}

function getAdapterLibraryImport(options: GenerateNPAClientOptions): string {
  if (options.adapterLibraryImport) {
    return options.adapterLibraryImport;
  }

  if (options.libraryImport) {
    return options.libraryImport;
  }

  return options.adapter === "mysql"
    ? MYSQL_LIBRARY_IMPORT
    : POSTGRESQL_LIBRARY_IMPORT;
}
