export type NPAErrorCode =
  | "NPA_CONFIG_NOT_FOUND"
  | "NPA_INVALID_CONFIG"
  | "NPA_UNSUPPORTED_ADAPTER"
  | "NPA_ADAPTER_REQUIRED"
  | "NPA_CONNECTOR_EXPORT_MISSING"
  | "NPA_REPOSITORY_METADATA_REQUIRED"
  | "NPA_DUPLICATE_REPOSITORY"
  | "NPA_ENTITY_METADATA_NOT_FOUND"
  | "NPA_ENTITY_ID_REQUIRED"
  | "NPA_COMPOSITE_RELATION_KEY_UNSUPPORTED"
  | "NPA_INVALID_DECORATOR_TARGET"
  | "NPA_INVALID_DECORATOR_OPTIONS"
  | "NPA_DUPLICATE_ENTITY_METADATA"
  | "NPA_UNSUPPORTED_CASCADE_TYPE"
  | "NPA_UNSUPPORTED_FETCH_TYPE"
  | "NPA_UNSUPPORTED_GENERATION_STRATEGY"
  | "NPA_SYMBOL_PROPERTY_UNSUPPORTED"
  | "NPA_INVALID_QUERY_METHOD"
  | "NPA_INVALID_QUERY_PREDICATE"
  | "NPA_QUERY_ARGUMENT_COUNT_MISMATCH"
  | "NPA_DUPLICATE_QUERY_PREDICATE"
  | "NPA_PAGEABLE_UNSUPPORTED_QUERY"
  | "NPA_TOP_PAGEABLE_CONFLICT"
  | "NPA_RAW_QUERY_PLACEHOLDER_MISMATCH"
  | "NPA_RAW_QUERY_RESULT_MODE_UNSUPPORTED"
  | "NPA_ORDER_DIRECTION_UNSUPPORTED"
  | "NPA_INVALID_PAGE_SIZE"
  | "NPA_INVALID_OFFSET_PAGE"
  | "NPA_INVALID_CURSOR"
  | "NPA_CURSOR_METADATA_REQUIRED"
  | "NPA_CURSOR_ORDER_UNSUPPORTED"
  | "NPA_CURSOR_DIRECTION_CONFLICT"
  | "NPA_RELATION_NOT_FOUND"
  | "NPA_RELATION_MAPPED_BY_REQUIRED"
  | "NPA_RELATION_MAPPED_BY_NOT_FOUND"
  | "NPA_RELATION_TARGET_ID_REQUIRED"
  | "NPA_RELATION_PRIMARY_VALUE_REQUIRED"
  | "NPA_TO_MANY_RELATION_ARRAY_REQUIRED"
  | "NPA_UNRESOLVED_TO_ONE_DEPENDENCY"
  | "NPA_RELATION_LOAD_METADATA_REQUIRED"
  | "NPA_PRIMARY_KEY_REQUIRED"
  | "NPA_COMPOSITE_ID_OBJECT_REQUIRED"
  | "NPA_INSERT_VALUES_REQUIRED"
  | "NPA_UPDATE_VALUES_REQUIRED"
  | "NPA_VERSION_COLUMN_REQUIRED"
  | "NPA_VERSION_VALUE_REQUIRED"
  | "NPA_OPTIMISTIC_LOCK_FAILED"
  | "NPA_READ_ONLY_TRANSACTION_WRITE"
  | "NPA_PERSIST_UNSUPPORTED"
  | "NPA_REMOVE_UNSUPPORTED"
  | "NPA_RELATION_SYNC_UNSUPPORTED"
  | "NPA_TRANSACTION_MANAGER_NOT_FOUND"
  | "NPA_TRANSACTION_MANAGER_DUPLICATED"
  | "NPA_TRANSACTION_MANAGER_AMBIGUOUS"
  | "NPA_TRANSACTION_DECORATOR_INVALID_TARGET"
  | "NPA_TRANSACTION_PROPAGATION_UNSUPPORTED"
  | "NPA_NESTED_TRANSACTION_UNSUPPORTED"
  | "NPA_ROLLBACK_ONLY"
  | "NPA_MIGRATION_DATABASE_URL_REQUIRED"
  | "NPA_MIGRATION_RENAME_DATABASE_URL_REQUIRED"
  | "NPA_MIGRATION_UNSUPPORTED_COMMAND"
  | "NPA_MIGRATION_INVALID_ARGUMENT"
  | "NPA_MIGRATION_INVALID_RENAME"
  | "NPA_MIGRATION_UNSAFE_STATEMENT"
  | "NPA_MIGRATION_LOCK_FAILED"
  | "NPA_MIGRATION_CHECKSUM_MISMATCH"
  | "NPA_MIGRATION_HISTORY_MISMATCH"
  | "NPA_MIGRATION_ENTITY_ID_REQUIRED"
  | "NPA_MIGRATION_SCHEMA_PARSE_FAILED"
  | "NPA_MIGRATION_UNSUPPORTED_DDL"
  | "NPA_DATABASE_QUERY_FAILED"
  | "NPA_DATABASE_UNIQUE_CONSTRAINT_FAILED"
  | "NPA_DATABASE_FOREIGN_KEY_CONSTRAINT_FAILED"
  | "NPA_DATABASE_NOT_NULL_CONSTRAINT_FAILED"
  | "NPA_DATABASE_INSERT_RETURN_FAILED"
  | "NPA_DATABASE_CONNECTION_INVALID"
  | "NPA_DATABASE_IDENTIFIER_INVALID"
  | "NPA_DATABASE_TRANSACTION_CONNECTION_INVALID";

export interface NPAErrorOptions {
  code: NPAErrorCode;
  cause?: unknown;
  details?: Record<string, unknown>;
}

export class NPAError extends Error {
  readonly code: NPAErrorCode;
  readonly cause?: unknown;
  readonly details?: Record<string, unknown>;

  constructor(message: string, options: NPAErrorOptions) {
    super(message);
    this.name = new.target.name;
    this.code = options.code;
    this.cause = options.cause;
    this.details = options.details;
  }
}

export class NPAConfigurationError extends NPAError {}
export class NPAMetadataError extends NPAError {}
export class NPAQueryError extends NPAError {}
export class NPAPaginationError extends NPAError {}
export class NPAMigrationError extends NPAError {}
export class NPATransactionError extends NPAError {}
export class NPAPersistenceError extends NPAError {}
export class NPADatabaseError extends NPAError {}
